<?xml version="1.0" encoding="utf-8"?>
<!--Assignment 1
  SENG1050*/
  NI ZENG*/
  C3238805*/
  DUE 18/09/2020*-->
<!DOCTYPE goholiday 
[
  <!ELEMENT goholiday (holidays*)>  
  
  <!ELEMENT holidays (cruise+)>
  
  <!ELEMENT cruise (packeage_name,description,cost,number_nights,popularity,accommodation+,coupon_code?,reviews*,picture+,url+,travel_date?,saved?)>  
  
  <!ELEMENT packeage_name (#PCDATA)>  
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT cost (#PCDATA)>  
  <!ELEMENT number_nights (#PCDATA )>
  <!ELEMENT popularity (#PCDATA)>
  
  <!ELEMENT accommodation (#PCDATA)>
  <!ATTLIST accommodation options (location|additional_cost) #REQUIRED>
  
  <!ELEMENT coupon_code (#PCDATA)>
  <!ELEMENT reviews (#PCDATA)>  
  <!ELEMENT picture (#PCDATA)>
  <!ELEMENT url (#PCDATA)>
  
  <!ELEMENT travel_date (date,month,year)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT month (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
   
  <!ELEMENT saved (#PCDATA)>
  <!ENTITY dollor "$">

]>

<goholiday>
	<holidays>	
		<cruise>
			<packeage_name>cruise packeage l1</packeage_name>
			<description>south pacific</description>
			<cost>$ 700</cost>
			<number_nights>7</number_nights>
			<popularity>3</popularity>
			<accommodation>single room suite</accommodation>
			<accommodation options= "additional_cost"> upgrad suite</accommodation>
			<coupon_code></coupon_code>
			<reviews></reviews>
			<picture>img\southpacific.jpg</picture>
			
			<url>https://www.flightcentre.com.au/product/12656327</url>
			
			<travel_date>
				<date></date>
				<month></month>
				<year></year>
			</travel_date>
			
			<saved>&dollor;</saved>			
		</cruise>

		<cruise>
			<packeage_name>cruise packeage l2</packeage_name>
			<description>barrier reef discovery</description>
			<cost>$ 800</cost>
			<number_nights>7</number_nights>
			<popularity>4</popularity>
			<accommodation>single room suite</accommodation>
			<accommodation options= "additional_cost"> upgrad suite</accommodation>
			<coupon_code></coupon_code>
			<reviews></reviews>
			<picture>img\barrier.jpg</picture>
			
			<url>https://www.pocruises.com.au/cruises/barrier-reef-discovery/x104#:~:text=We%20dedicate%20this%20itinerary%20to,with%20Australia%20all%20over%20again.</url>
			
			<travel_date>
				<date></date>
				<month></month>
				<year></year>
			</travel_date>
			
			<saved>&dollor;</saved>			
		</cruise>
		
		<cruise>
			<packeage_name>cruise packeage l3</packeage_name>
			<description>queensland cruise</description>
			<cost>$ 900</cost>
			<number_nights>7</number_nights>
			<popularity>3</popularity>
			<accommodation>single room suite</accommodation>
			<accommodation options= "additional_cost"> upgrad suite</accommodation>
			<coupon_code></coupon_code>
			<reviews></reviews>
			<picture>img\queensland.jpg</picture>
			
			<url>https://www.flightcentre.com.au/product/9314691</url>
			
			<travel_date>
				<date></date>
				<month></month>
				<year></year>
			</travel_date>
			
			<saved>&dollor;</saved>			
		</cruise>
		
	</holidays>
</goholiday>

